### ISSUE TITLE
workspace_root is mixed up with RIOTBASE

### ISSUE THREAD

**Issue by keestux** [attdona/riot-code#11]
In the current implementation workspace_root is changed to point at RIOTBASE, if RIOT is added as a workspace folder to the project.

Say for example I have `~/RIOT-Projects/hello` for a new project. I want `~/RIOT-Projects/hello` to be my `workspace_root`. Also I configure the workspace with a subdirectory `src` as the "build" directory. RIOT-OS is installed somewhere else on my system. Here is how my code-workspace looks like.

```
{
	"folders": [
		{
			"path": "."
		},
		{
			"path": "/home/kees/src/RIOT"
		}
	],
	"settings": {
		"riot.build_dir": "src",
		"editor.tabSize": 8,
		"riot.compiler": "arm-none-eabi-gcc",
		"riot.board": "sodaq-sff",
		"riot.make_defs": "QUIET=1 USB_VID=2341 USB_PID=804d",
		"files.exclude": {
			"**/*~": true
		}
	}
}
```

So, I have added RIOT as a workspace folder. Unfortunately the plugin is modifying `workspace_root`. And now it is trying to find `src` in the RIOT code. And it looks like it is attempting to modify my vscode setting in the RIOT folder. Hmm, I don't like that.

If I don't add RIOT as a workspace folder then "RIOT init" doesn't do anything.

What I propose is to somehow separate `RIOTBASE` and `workspace_root`. And maybe even to add something like `riot.base` to the config.

**Comment by attdona** [comment]
Thanks for reporting the problem! 

The following fixes in v0.1.6:

 - `RIOTBASE` is now managed with `riot.base` config setting.

 - Removed unuseful `project.workspace_root`.

Before publishing on vscode marketplace I need some more regression test, in the meantime it should be great if you could verify if this version works in your setup.

**Comment by keestux** [comment]
That was quick.
BTW I was trying some changes myself and have something that works for me. But I wasn't done yet.

**Comment by keestux** [comment]
Are you open for criticism? I have a number of remarks about the recent commits, and about the project in general.

**Comment by attdona** [comment]
Yes! Let me know ...

**Comment by keestux** [comment]
Let's start with a few points.
1. versions, you should follow semver more closely (see https://semver.org/#semantic-versioning-200). Don't be afraid to use v1.0.0 (Dijkstra is not coming to haunt you, I think he wanted version 1 to be perfect.)
2. in commit c459abe you included too many, seemingly unrelated changes. For one, you added a semicolon to all statements. This should have gone in a separate commit. Also whitespace changes should better go in a separate commit.

**Comment by keestux** [comment]
3. create commits with clear comments. "fixes # 11" or just "fixes" is a bad commit message. Follow the commonly accepted format of commit messages (for example https://chris.beams.io/posts/git-commit/)

**Comment by keestux** [comment]
4. create a working branch for the changes (even if it is in your own Git repo), and create a merge commit when you're done. This will keep the master clean until changes are ready to be merged. This also allows others to test the development branch before it is merged.

**Comment by attdona** [comment]
Hi Keestux,
many thanks for the feedback. It all make sense.

I will read the guidelines about git comments and semver and I'll try to reach out with a consistent style.

Sorry for the mess up of the unrelated and global changes about whitespaces and semi-colon at eol: I changed my vscode prettier rules about formatting and changes got automatically into the commit ...

probably it make sense stabilize and documents the project coding guidelines.
