### ISSUE TITLE
RIOT init hangs with "RIOT setup, please wait..."

### ISSUE THREAD

**Issue by keestux** [attdona/riot-code#14]
Today I suddenly start seeing the "RIOT setup, please wait ..." message when I do RIOT init. It shows that message forever. And it does not update `riotbuild.h` anymore.

I also upgrade my vscode program to 1.40.1 (but that didn't help).

**Comment by attdona** [comment]
I've reproduced the problem upgrading `node` on my machine to v13.1.0

Did you make the same?

**Comment by keestux** [comment]
I'm on Ubuntu 18.04. It has package `nodejs`.
```
$ node -v
v8.10.0
```

What do you mean by: "I've reproduced the problem upgrading node on my machine to v13.1.0" ? Does it mean you have the problem too, with node v13.1.0?

**Comment by attdona** [comment]
I've noticed the problem after updating node, but absolutly not sure that the problem is related to node versions.

After seeing [this note](https://github.com/shelljs/shelljs/wiki/Electron-compatibility) i've tried to set `config.execPath` and it seems to resolve the problem, at least on linux.

**Comment by keestux** [comment]
This seems to help for me.

**Comment by keestux** [comment]
Side note.

It's a better practice to make a branch. Then create commits, test etc. And when you satisfied you can merge into the master branch.
This gives you the chance to make changes, rebase, undo, squash before you actually merge it in master.

**Comment by keestux** [comment]
Side note2.
Create a tag for a release. And follow the semver [1] strategy. For this issue, I'd say that v1.0.1 is the right choice.
[1] https://semver.org/

**Comment by keestux** [comment]
@attdona are you planning to release a new version? Right now I can only use vscode with RIOT by running the vscode debugger.

**Comment by attdona** [comment]
Just published v1.0.1.

Attilio

**Comment by keestux** [comment]
Thanks
