### ISSUE TITLE
Features request : add toolchain location to PATH

### ISSUE THREAD

**Issue by dylad** [attdona/riot-code#5]
Hi,
I would like to know if it is possible to add a new variable in User/setting.json file to add the toolchain location to the PATH variable.
In my case, I have different version of arm-none-eabi-gcc install under /usr and I would like to easily switch between them.
Currently the only solution I've found is the following : 
`    "terminal.integrated.env.linux": {"PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/dylan/Software/nordic/nRF5x-Command-Line-Tools_9_7_1_Linux-x86_64/nrfjprog:/usr/gcc-arm-none-eabi-5_4-2016q3/bin"},`

But I had to rewrite the whole PATH variable within User/settings.json which is not very convenient.

Maybe there is a better way but I didn't find it yet.

**Comment by attdona** [comment]
Yes, it should be possible, something like:
   
    # default: riot.compiler_path: ""  => get from PATH
    riot.compiler_path: /usr/gcc-arm-none-eabi-5_4-2016q3/bin # add in front of PATH, get compiler built-in includes and launch make

Let me think about that ...

Another alternative is to set the `PATH` variable before launching `code` from the terminal.

**Comment by dylad** [comment]
> Another alternative is to set the PATH variable before launching code from the terminal.

I thought about that but I'm used to launch vscode using an applet... and I don't really like to close/reopen vscode each time I want to switch my compiler.

**Comment by attdona** [comment]
Implemented in version 0.1.1.

Let me know!
Greetings
Attilio

**Comment by dylad** [comment]
I just give it a try on linux but it doesn't work :(
look like the PATH variable is not updated with the toolchain path so vscode doesn't find arm-none-eabi-gcc.
Am I missing something ?
Here is my user's config : 
```
{
    // Objet avec les variables d’environnement qui seront ajoutées au processus VS Code pour être utilisées par le terminal sous Linux
    //"terminal.integrated.env.linux": {"PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/dylan/Software/nordic/nRF5x-Command-Line-Tools_9_7_1_Linux-x86_64/nrfjprog:/usr/gcc-arm-none-eabi-5_4-2016q3/bin"},
    
    // RIOT target board
    "riot.board": "saml21-xpro",

    // make working dir
    "riot.build_dir": "tests/shell",

    // compiler name used for retrieving system includes
    "riot.compiler": "arm-none-eabi-gcc",

    // verbose output setting
    "riot.quiet": "QUIET=1",

    "riot.compiler_path": "/usr/gcc-arm-none-eabi-5_4-2016q3/bin/",
}
```

**Comment by attdona** [comment]
The setting is right. 

Just to be sure, check it for some reason you have redefined riot.compiler_path into `Workspace Setting` because it take precedence over `User Setting`

**Comment by dylad** [comment]
My Workspace setting is completely empty 
```
{
}
```

**Comment by attdona** [comment]
My fault, I miss a trivial test case! I was able to reproduce the problem.
Before releasing a patch, please manually change the build `command` in your `.vscode/tasks.json`:

        "tasks": [
            {
                "label": "build: hello-world",
                "type": "shell",
                "command": "PATH=${config:riot.compiler_path}:$PATH make",

Does it works now?

**Comment by dylad** [comment]
@attdona Yes it works ! Thanks a lot for your amazing work :)
