### ISSUE TITLE
build job failure on ubuntu 18.04

### ISSUE THREAD

**Issue by dylad** [attdona/riot-code#8]
I'm facing a weird bug using the lastest ubuntu and lastest vscode.

I used a downloaded toolchain (the one in ubuntu repo is broken) and each time I try to compile i get :  
```
> Executing task: 'PATH=/home/heik/Bureau/gcc-arm-none-eabi-7-2018-q2-update/bin:$PATH make' QUIET=1 BOARD=saml21-xpro <

/bin/bash: PATH=/home/heik/Bureau/gcc-arm-none-eabi-7-2018-q2-update/bin:$PATH make: Aucun fichier ou dossier de ce type
Le processus du terminal s'est achevé avec le code de sortie 127
```

I have the following parameters set (user settings) : 
```
      // RIOT target board
  "riot.board": "saml21-xpro",

// make working dir
"riot.build_dir": "examples/hello-world",

// compiler name used for retrieving system includes
"riot.compiler": "arm-none-eabi-gcc",

// override default compiler configured with PATH env
"riot.compiler_path": "/home/heik/Bureau/gcc-arm-none-eabi-7-2018-q2-update/bin",

// verbose output setting
"riot.quiet": "QUIET=1",
```

Looks like there is some issue with the args in tasks.json because if I remove the following
```
            "args": [
                "${config:riot.quiet}",
                "BOARD=${config:riot.board}"
            ],
```

and hardcoded them here
`"command": "PATH=${config:riot.compiler_path}:$PATH make",`

I'm able to compile but this is override each time I change a setting :/

**Comment by attdona** [comment]
Hi @dylad, I was able to reproduce the issue with the latest version of vscode. I will fix the problem as soon as possible.

In the meantime, if it is not a problem, a workaround should be to delete `riot.compiler_path` from user settings and to set PATH env to your toolchain:

    > export PATH=/home/heik/Bureau/gcc-arm-none-eabi-7-2018-q2-update/bin:$PATH
    > code

**Comment by dylad** [comment]
For now I'll use the integrated terminal and manually make.
Does the problem is related to riot.compiler_path ? I thought it was related to the args.
Anyway, thanks for handling this !

**Comment by attdona** [comment]
I dont know why things changed, but the problem is related to how vscode compose shell commands, with the current version you have a string like:

    'PATH=/home/heik/Bureau/gcc-arm-none-eabi-7-2018-q2-update/bin:$PATH make' QUIET=1 BOARD=saml21-xpro

before the command was correctly formatted as:

    PATH=/home/heik/Bureau/gcc-arm-none-eabi-7-2018-q2-update/bin:$PATH make QUIET=1 BOARD=saml21-xpro

**Comment by dylad** [comment]
Dunno either, but it seems to be a very recent change.

**Comment by dylad** [comment]
@attdona can you update the vscode module so I can give it a try whenever you find some time please ?

**Comment by dylad** [comment]
@attdona vscode module is still at 0.1.2 after your commit, am i missing something ?

**Comment by attdona** [comment]
I have to publish yet on marketplace, just updated github.

Unzip the below vsix package and load with vscode (command `Extensions: Install From VSIX`)

[riot-0.1.3.vsix.gz](https://github.com/attdona/riot-code/files/2148722/riot-0.1.3.vsix.gz)

Let me know!

**Comment by dylad** [comment]
It works like a charm ! Thanks a lot for fixing this !
I'm closing the issue.
