### ISSUE TITLE
RIOT init fails if we use custom bin directory

### ISSUE THREAD

**Issue by bluephoton** [attdona/riot-code#9]
In my environment, I defined new bindir as follows:

BINDIRBASE ?= $(CURDIR)/../../bin

it appears that riot-code assumes that bin is always under make folder, hence it fails. will be great to have a config value where we can provide relative path for bindir as this is common scenario.

**Comment by attdona** [comment]
With riot-code v.0.1.4 it is possible to define a custom value for BINDIRBASE using the setting
 `Riot: Make_defs` in `Setting` or `riot.make_defs` in `setting.json`, for example:

    "riot.make_defs": "QUIET=0 BINDIRBASE=/tmp/riot_bin"
